//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animals 
    {
        public int  Id { get; set; } 
        public string Animal1 { get; set; }
        public Nullable<bool> hasFur { get; set; }
        public Nullable<bool> isBird { get; set; }
        public Nullable<bool> eatsFruit { get; set; }
        public Nullable<bool> huntsRabbit { get; set; }

    }
}
